clustering:
  maxBlockDiff: 10000
  maxETHDiff: 0.01

log:
  level: info

database:
  address : "127.0.0.1:3307"
  user : "root"
  password : "admin"
  name : "test"
  driver : "mysql"

ethereum:
  address : "ws://localhost:59048"