clustering:
  maxBlockDiff: 10000
  maxETHDiff: 0.01

log:
  level: debug

database:
  address : "127.0.0.1:3306"
  user : "root"
  password : "testPASS25!"
  name : "test"
  driver : "mysql"
  clean: false

ethereum:
  address : "http://localhost:8545"